"""added complaint to square category enum

Revision ID: 0865596cfa01
Revises: 8ecb76e5a8c5
Create Date: 2026-08-03 17:52:08.473246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0865596cfa01'
down_revision: Union[str, Sequence[str], None] = '8ecb76e5a8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE squarecategory ADD VALUE 'COMPLAINT';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
