"""Updated Notice Comment model

Revision ID: 0cdf9ed0a755
Revises: 3128760cfc00
Create Date: 2026-07-19 15:49:32.243054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdf9ed0a755'
down_revision: Union[str, Sequence[str], None] = '3128760cfc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice_comments', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'notice_comments', 'notice_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notice_comments', type_='foreignkey')
    op.drop_column('notice_comments', 'parent_id')
    # ### end Alembic commands ###
