"""added roll number column to user model

Revision ID: 1790282c185d
Revises: 6077fa164d07
Create Date: 2026-07-22 13:52:21.948087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1790282c185d'
down_revision: Union[str, Sequence[str], None] = '6077fa164d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('extract_roll_from_email', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('roll_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roll_number')
    op.drop_column('institutions', 'extract_roll_from_email')
    # ### end Alembic commands ###
