"""updated chat tables for club and team structure

Revision ID: 1ab9d886d887
Revises: 34b45c3542d2
Create Date: 2026-08-14 18:03:03.024052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab9d886d887'
down_revision: Union[str, Sequence[str], None] = '34b45c3542d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_participants', sa.Column('is_lead', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'conversations', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'parent_id')
    op.drop_column('conversation_participants', 'is_lead')
    # ### end Alembic commands ###
