"""added is blocked column to institutions table

Revision ID: 30baeb8b0bce
Revises: c7ae4df9cee5
Create Date: 2026-08-16 18:21:26.826630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30baeb8b0bce'
down_revision: Union[str, Sequence[str], None] = 'c7ae4df9cee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'is_blocked')
    # ### end Alembic commands ###
