"""added recovery email to user model

Revision ID: 4940ed51a4c5
Revises: ab031d239f8a
Create Date: 2026-08-12 23:41:47.620715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4940ed51a4c5'
down_revision: Union[str, Sequence[str], None] = 'ab031d239f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_email')
    # ### end Alembic commands ###
