"""added is_delevered column to Message table

Revision ID: 4abfac95055c
Revises: 1790282c185d
Create Date: 2026-07-23 12:45:08.036370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abfac95055c'
down_revision: Union[str, Sequence[str], None] = '1790282c185d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_delivered')
    # ### end Alembic commands ###
