"""update_schemas_for_admin_head

Revision ID: 4e8e4dc4259b
Revises: f8451622b5b1
Create Date: 2026-06-29 14:08:34.062426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8e4dc4259b'
down_revision: Union[str, Sequence[str], None] = 'f8451622b5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('requires_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requires_password_change')
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
