"""added notice votes model

Revision ID: 600194825b66
Revises: 0865596cfa01
Create Date: 2026-08-03 18:22:30.615618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600194825b66'
down_revision: Union[str, Sequence[str], None] = '0865596cfa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    op.add_column('notices', sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('notices', sa.Column('downvote_count', sa.Integer(), server_default='0', nullable=False))
    
    op.create_table('notice_votes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('notice_id', sa.String(), nullable=False),
        sa.Column('vote_type', postgresql.ENUM('UPVOTE', 'DOWNVOTE', name='votetype', create_type=False), nullable=False),
        sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_votes_id'), 'notice_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'downvote_count')
    op.drop_column('notices', 'upvote_count')
    op.drop_index(op.f('ix_notice_votes_id'), table_name='notice_votes')
    op.drop_table('notice_votes')
    # ### end Alembic commands ###
