"""added department id to various models

Revision ID: 6077fa164d07
Revises: ceb14477a829
Create Date: 2026-07-21 01:23:00.122712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6077fa164d07'
down_revision: Union[str, Sequence[str], None] = 'ceb14477a829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('name', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('department_id', sa.String(), nullable=True))
    op.create_foreign_key('conversations_department_id_fkey', 'conversations', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('department_id', sa.String(), nullable=True))
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_constraint('conversations_department_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'department_id')
    op.drop_column('conversations', 'name')
    # ### end Alembic commands ###
