"""updated User model with last seen and is online fields

Revision ID: 67af2fa9d1ae
Revises: 4abfac95055c
Create Date: 2026-07-23 13:45:46.873278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67af2fa9d1ae'
down_revision: Union[str, Sequence[str], None] = '4abfac95055c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
