"""added post attachments and comments

Revision ID: 7f694e28e549
Revises: 37fe1c4ec425
Create Date: 2026-07-18 12:03:13.580451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f694e28e549'
down_revision: Union[str, Sequence[str], None] = '37fe1c4ec425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notice_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_comments_id'), 'notice_comments', ['id'], unique=False)
    op.add_column('notices', sa.Column('urgent_until', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('notices', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('file_url', sa.String(), nullable=True))
    op.drop_column('notices', 'is_urgent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('is_urgent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('notices', 'file_url')
    op.drop_column('notices', 'image_url')
    op.drop_column('notices', 'urgent_until')
    op.drop_index(op.f('ix_notice_comments_id'), table_name='notice_comments')
    op.drop_table('notice_comments')
    # ### end Alembic commands ###
