"""added storage model and updated registration models

Revision ID: 8ecb76e5a8c5
Revises: a744f53d6b03
Create Date: 2026-07-27 10:16:35.836201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecb76e5a8c5'
down_revision: Union[str, Sequence[str], None] = 'a744f53d6b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_file_hash'), 'file_assets', ['file_hash'], unique=True)
    op.create_index(op.f('ix_file_assets_id'), 'file_assets', ['id'], unique=False)
    op.add_column('institutions', sa.Column('default_storage_limit', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('storage_used', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('storage_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_limit')
    op.drop_column('users', 'storage_used')
    op.drop_column('institutions', 'default_storage_limit')
    op.drop_index(op.f('ix_file_assets_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_file_hash'), table_name='file_assets')
    op.drop_table('file_assets')
    # ### end Alembic commands ###
