"""added campaign fields to institutions table

Revision ID: 95e7243cc970
Revises: a534d5dfe95b
Create Date: 2026-08-09 16:20:46.000110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e7243cc970'
down_revision: Union[str, Sequence[str], None] = 'a534d5dfe95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('campaign_version_id', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('show_popup', sa.Boolean(), nullable=True))
    op.add_column('institutions', sa.Column('popup_title', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('popup_message', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('lottie_url', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('target_route', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('show_banner', sa.Boolean(), nullable=True))
    op.add_column('institutions', sa.Column('banner_title', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('banner_message', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('banner_action_url', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('primary_color_hex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'primary_color_hex')
    op.drop_column('institutions', 'banner_action_url')
    op.drop_column('institutions', 'banner_message')
    op.drop_column('institutions', 'banner_title')
    op.drop_column('institutions', 'show_banner')
    op.drop_column('institutions', 'target_route')
    op.drop_column('institutions', 'lottie_url')
    op.drop_column('institutions', 'popup_message')
    op.drop_column('institutions', 'popup_title')
    op.drop_column('institutions', 'show_popup')
    op.drop_column('institutions', 'campaign_version_id')
    # ### end Alembic commands ###
