"""added bazaar product and saved product tables

Revision ID: a534d5dfe95b
Revises: 600194825b66
Create Date: 2026-08-09 00:46:59.363577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a534d5dfe95b'
down_revision: Union[str, Sequence[str], None] = '600194825b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bazaar_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('TEXTBOOK', 'ELECTRONICS', 'FURNITURE', 'CLOTHING', 'STATIONERY', 'OTHER', name='bazaarcategory'), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', name='itemcondition'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bazaar_products_id'), 'bazaar_products', ['id'], unique=False)
    op.create_table('saved_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['bazaar_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_products_id'), 'saved_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_products_id'), table_name='saved_products')
    op.drop_table('saved_products')
    op.drop_index(op.f('ix_bazaar_products_id'), table_name='bazaar_products')
    op.drop_table('bazaar_products')
    # ### end Alembic commands ###
