"""updated chat models for hub and added a new enum

Revision ID: aa45a1a443dd
Revises: 4940ed51a4c5
Create Date: 2026-08-14 09:53:26.289607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa45a1a443dd'
down_revision: Union[str, Sequence[str], None] = '4940ed51a4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE hubprivacy AS ENUM ('PUBLIC', 'PRIVATE', 'INVITE_ONLY')")
    op.add_column('conversation_participants', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('conversation_participants', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('privacy', sa.Enum('PUBLIC', 'PRIVATE', 'INVITE_ONLY', name='hubprivacy'), server_default='PUBLIC', nullable=False))
    op.add_column('conversations', sa.Column('institution_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'institution_id')
    op.drop_column('conversations', 'privacy')
    op.drop_column('conversations', 'avatar_url')
    op.drop_column('conversations', 'description')
    op.drop_column('conversation_participants', 'is_approved')
    op.drop_column('conversation_participants', 'is_admin')
    op.execute("DROP TYPE hubprivacy")
    # ### end Alembic commands ###
