"""added random to square category enum

Revision ID: ab031d239f8a
Revises: 95e7243cc970
Create Date: 2026-08-10 18:51:18.850707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab031d239f8a'
down_revision: Union[str, Sequence[str], None] = '95e7243cc970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE squarecategory ADD VALUE 'RANDOM';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
