"""updated Message model with is edited column

Revision ID: b66a86e9734b
Revises: 67af2fa9d1ae
Create Date: 2026-07-24 01:01:54.154445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66a86e9734b'
down_revision: Union[str, Sequence[str], None] = '67af2fa9d1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
