"""updated Conversation Participant  model with is blocked column

Revision ID: b7c46fc759a5
Revises: b66a86e9734b
Create Date: 2026-07-24 13:20:37.986378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c46fc759a5'
down_revision: Union[str, Sequence[str], None] = 'b66a86e9734b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_participants', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_participants', 'is_blocked')
    # ### end Alembic commands ###
