"""advanced chat features

Revision ID: ceb14477a829
Revises: 0cdf9ed0a755
Create Date: 2026-07-20 01:05:41.688227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb14477a829'
down_revision: Union[str, Sequence[str], None] = '0cdf9ed0a755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_foreign_key('messages_reply_to_id_fkey', 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_reply_to_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
